### ISSUE TITLE
Dropdown styling doesn't work in IE

### ISSUE THREAD

**Issue by timReynolds** [trussle/trussle-style#5]
When using IE 11 the dropdown styling is incorrect as the default dropdown arrow is show to the left of the image. 

<img width="252" alt="2017-01-03_11-16-25" src="https://cloud.githubusercontent.com/assets/168870/21606283/34c4c3da-d163-11e6-8ddc-f6edd3c3aae7.png">

**Comment by jonnyarnold** [comment]
Fixed in v0.1.9.
